const disney = [
    [1, "Jungle Book", "The Bare Necessities"],
    [2, "Mary Poppins", "Spoonful of Sugar"],
    [3, "The Little Mermaid", "Under the Sea"],
    [4, "Snow White", "Heigh Ho"],
    [5, "Aladdin", "A Whole New World"],
    [6, "Pinocchio", "When you Wish Upon a Star"],
    [7, "Beauty & The Beast", "Belle"],
    [8, "Jungle Book", "I Wanna be like You (The Monkey Song)"],
    [9, "Pocahontas", "Just Around the River Bend"],
    [10, "Dumbo", "When I see an Elephant Fly"],
    [11, "Toy Story", "You've got a friend in me"],
    [12, "Mary Poppins", "Lets Go Fly a Kite"],
    [13, "Lion King", "Hakuna Matata"],
    [14, "Toy Story 2", "When She Loved Me"],
    [15, "The Lion King", "I Just Can't Wait to be King"],
    [16, "101 Dalmations", "Cruella De Vil"],
    [17, "Winnie the Pooh", "The Wonderful Thing About Tiggers"],
    [18, "The Lion King", "Can You Feel the Love Tonight"],
    [19, "Sleeping Beauty", "Once Upon a Dream"],
    [20, "The Little Mermaid", "Part of Your World"],
    [21, "Beauty and the Beast", "Be Our Guest"],
    [22, "The Little Mermaid", "Kiss the Girl"],
    [23, "The Lion King", "Circle of Life"],
    [24, "Cinderella", "A Dream is a Wish your Heart Makes"],
    [25, "Mary Poppins", "Supercalifragilisticexpialidocious"],
    [26, "The Aristocats", "Everybody Wants to be a Cat"],
    [27, "Song of the South", "Zip-a-dee-doo-dah"],
    [28, "Snow White and the Seven Dwarfs", "Dig, Dig, Dig, Heigh-Ho"],
    [29, "Dumbo", "Elephants on Parade"],
    [30, "Pinocchio", "Give a Little Whistle"],
    [31, "Peter Pan", "You Can Fly, You Can Fly, You Can Fly"],
    [32, "Tangled", "I See the Light"],
    [33, "Frozen", "Let It Go"],
    [34, "The Princess and the Frog", "Almost There"],
    [35, "Pocahontas", "Colours of the Wind"],
    [36, "Tangled", "I've Got a Dream"],
    [37, "Aladdin (King of Thieves)", "Out of Thin Air"],
    [38, "Mulan", "Reflection"],
    [39, "Cinderella", "So This is Love"],
    [40, "Enchanted", "That's How You Know"],
    [41, "Enchanted", "True Loves Kiss"],
    [42, "Tangled", "When Will My Life Begin"],
    [43, "Moana", "Tulou Tagaloa"],
    [44, "Moana", "Shiny"],
    [45, "Beauty and the Beast", "Beauty and the Beast"],
    [46, "Mary Poppins", "Chim Chim Cher-ee"],
    [47, "Frozen", "Do you want to Build a Snowman"],
    [48, "Pinnochio", "Give a Little Whistle"],
    [49, "Pinnochio", "Hi Diddle Dee Dee (An Actor's Life for me)"],
    [50, "Moana", "How Far I'll Go"]


];