const eighties = [
    [1, "Billy Joel", "Uptown Girl"],
    [2, "Weathergirls", "Raining Men"],
    [3, "Dexys Midnight Runners", "Come On Eileen"],
    [4, "Michael Jackson", "Way You Make Me Feel"],
    [5, "Tina Turner", "Simply the Best"],
    [6, "Michael Jackson", "Smooth Criminal"],
    [7, "Musical Youth", "Pass the Dutchie"],
    [8, "Wham!", "Wake me up before you go go"],
    [9, "A-Ha", "Take On Me"],
    [10, "Eurythmics", "Sweet Dreams (Are Made of This)"],
    [11, "Falco", "Rock Me Amadeus"],
    [12, "The Jam", "Town Called Malice"],
    [13, "Salt N Pepper", "Push It"],
    [14, "Cyndi Lauper", "Girls Just Wanna Have Fun"],
    [15, "Frankie Goes to Hollywood", "Relax"],
    [16, "UB40", "Red Red Wine"],
    [17, "Michael Jackson", "Bad"],
    [18, "Fleetwood Mac", "Everywhere"],
    [19, "Michael Jackson", "Beat It"],
    [20, "Blondie", "The Tide is High"],
    [21, "Madonna", "Like a Prayer"],
    [22, "Tiffany", "I Think We're Alone Now"],
    [23, "Bryan Adams", "Summer of 69"],
    [24, "Run DMC", "Walk This Way"],
    [25, "Survivor", "Eye of the Tiger"],
    [26, "DNA ft. Suzanne Vega", "Tom's Diner"],
    [27, "The Bangles", "Walk Like an Egyptian"],
    [28, "Phil Collins", "In the Air Tonight"],
    [29, "Michael Jackson", "Thriller"],
    [30, "Queen", "Another One Bites the Dust"],
    [31, "Madonna", "Like a Virgin"],
    [32, "Tears for Fears", "Shout"],
    [33, "Men Without Hats", "The Safety Dance"],
    [34, "DireStraits", "Walk of Life"],
    [35, "Eurythmics", "There Must Be An Angel"],
    [36, "The Police", "Every Breath You Take"],
    [37, "U2", "Pride (In the Name of Love)"],
    [38, "Peter Gabriel", "Sledgehammer"],
    [39, "Ray Parker Junior", "Ghostbusters"],
    [40, "Diana Ross", "Chain Reaction"],
    [41, "Phil Collins", "You Can't Hurry Love"],
    [42, "Frankie Goes to Hollywood", "Two Tribes"],
    [43, "Joan Jett and the Blackhearts", "I Love Rock N Roll"],
    [44, "Culture Club", "Karma Chameleon"],
    [45, "Belinda Carlisle", "Heaven is a Place on Earth"],
    [46, "The Proclaimers", "I'm Gonna Be (500 Miles)"],
    [47, "Heaven 17", "Temptation"],
    [48, "Yazoo", "Don't Go"],
    [49, "Kim Wilde", "Kids In America"],
    [50, "Chris Isaak", "Wicked Game"],
    [51, "Kate Bush", "Cloudbusting"],
    [52, "Paula Abdul", "Straight Up"],
    [53, "Peter Schilling", "Major Tom"],
    [54, "Rick James", "Super Freak"],
    [55, "Robbie Dupree", "Steal Away"],
    [56, "Roxette", "Listen To Your Heart"],
    [57, "Roxette", "The Look"],
    [58, "Steve Miller Band", "Abracadabra"],
    [59, "Patty Smyth", "The Warrior"],
    [60, "Talking Heads", "Burning Down the House"],
    [61, "Tears For Fears", "Head Over Heels"],
    [62, "The B-52's", "Love Shack"],
    [63, "The Pointer Sisters", "I'm So Excited"],
    [64, "The Waitresses", "I Know What Boys Like"],
    [65, "Tommy Tutone", "8675309 Jenny Jenny"],
    [66, "Wall Of Voodoo", "Mexican Radio"],
    [67, "Aerosmith", "Dude (Looks Like A Lady)"],
    [68, "Animotion", "Obsession"],
    [69, "Big Country", "In A Big Country"],
    [70, "Ozzy Osbourne", "Crazy Train"],
    [71, "Bobby McFerrin", "Don't Worry Be Happy"],
    [72, "Bonnie Tyler", "Holding Out for a Hero"],
    [73, "Chris de Burgh", "The Lady In Red"],
    [74, "Cyndi Lauper", "Time After Time"],
    [75, "Fine Young Cannibals", "Good Thing"],
    [76, "Foreigner", "Cold as Ice"],
    [77, "Pat Benatar", "Heartbreaker"],
    [78, "George Harrison", "Got My Mind Set On You"],
    [79, "Glenn Frey", "The Heat Is On"],
    [80, "Golden Earring", "Twilight Zone"],
    [81, "Harold Faltermeyer", "Axel F"],
    [82, "Heart", "These Dreams"],
    [83, "Huey Lewis & The News", "Hip To Be Square"],
    [84, "John Waite", "Missing You"],
    [85, "Kajagoogoo", "Too Shy"],
    [86, "Madness", "Our House"],
    [87, "Madonna", "Material Girl"],
    [88, "Matthew Wilder", "Break My Stride"],
    [89, "Men At Work", "Down Under"],
    [90, "Midnight Oil", "Beds Are Burning"],
    [91, "Mr. Mister", "Broken Wings"],
    [92, "Nu Shooz", "I Can't Wait"],

];