const eighties = [
    [1, "Billy Joel", "Uptown Girl"],
    [2, "Weathergirls", "Raining Men"],
    [3, "Dexys Midnight Runners", "Come On Eileen"],
    [4, "Michael Jackson", "Way You Make Me Feel"],
    [5, "Tina Turner", "Simply the Best"],
    [6, "Michael Jackson", "Smooth Criminal"],
    [7, "Musical Youth", "Pass the Dutchie"],
    [8, "Wham!", "Wake me up before you go go"],
    [9, "A-Ha", "Take On Me"],
    [10, "Eurythmics", "Sweet Dreams (Are Made of This)"],
    [11, "Falco", "Rock Me Amadeus"],
    [12, "The Jam", "Town Called Malice"],
    [13, "Salt N Pepper", "Push It"],
    [14, "Cyndi Lauper", "Girls Just Wanna Have Fun"],
    [15, "Frankie Goes to Hollywood", "Relax"],
    [16, "UB40", "Red Red Wine"],
    [17, "Michael Jackson", "Bad"],
    [18, "Fleetwood Mac", "Everywhere"],
    [19, "Michael Jackson", "Beat It"],
    [20, "Blondie", "The Tide is High"],
    [21, "Madonna", "Like a Prayer"],
    [22, "Tiffany", "I Think We're Alone Now"],
    [23, "Bryan Adams", "Summer of 69"],
    [24, "Run DMC", "Walk This Way"],
    [25, "Survivor", "Eye of the Tiger"],
    [26, "DNA ft. Suzanne Vega", "Tom's Diner"],
    [27, "The Bangles", "Walk Like an Egyptian"],
    [28, "Phil Collins", "In the Air Tonight"],
    [29, "Michael Jackson", "Thriller"],
    [30, "Queen", "Another One Bites the Dust"],
    [31, "Madonna", "Like a Virgin"],
    [32, "Tears for Fears", "Shout"],
    [33, "Men Without Hats", "The Safety Dance"],
    [34, "DireStraits", "Walk of Life"],
    [35, "Eurythmics", "There Must Be An Angel"],
    [36, "The Police", "Every Breath You Take"],
    [37, "U2", "Pride (In the Name of Love)"],
    [38, "Peter Gabriel", "Sledgehammer"],
    [39, "Ray Parker Junior", "Ghostbusters"],
    [40, "Diana Ross", "Chain Reaction"],
    [41, "Phil Collins", "You Can't Hurry Love"],
    [42, "Frankie Goes to Hollywood", "Two Tribes"],
    [43, "Joan Jett and the Blackhearts", "I Love Rock N Roll"],
    [44, "Culture Club", "Karma Chameleon"],
    [45, "Belinda Carlisle", "Heaven is a Place on Earth"],
    [46, "The Proclaimers", "I'm Gonna Be (500 Miles)"],
    [47, "Heaven 17", "Temptation"],
    [48, "Yazoo", "Don't Go"],
    [49, "Kim Wilde", "Kids In America"],
    [50, "Chris Rea", "Wicked Game"],
    [51, "Kate Bush", "Cloudbusting"],

];