const nineties = [
    [1, "Radiohead", "Creep"],
    [2, "Eminem", "Slim Shady"],
    [3, "New Radicals", "You Get What You Give"],
    [4, "Sixpence None the Richer", "Kiss Me"],
    [5, "Ice Cube", "It Was a Good day"],
    [6, "Sir MixAlot", "Baby Got Back"],
    [7, "Joan Osborne", "One of Us"],
    [8, "Shania Twain", "That Don't Impress Me Much"],
    [9, "Wyclef Jean", "Staying Alive"],
    [10, "Snoop Doggy Dogg", "What's My Name"],
    [11, "The B52's", "Love Shack"],
    [12, "Cypress Hill", "Insane In the Brain"],
    [13, "Naughty by Nature", "OPP"],
    [14, "Foo Fighters", "Everlong"],
    [15, "En Vogue", "My Lovin'"],
    [16, "2 Pac", "California Love"],
    [17, "Blackstreet", "No Diggity"],
    [18, "Propellerheads", "History Repeating"],
    [19, "Ricky Martin", "Livin' La Vida Loca"],
    [20, "Sarah McLachlan", "Posession"],
    [21, "Hanson", "MMMBop"],
    [22, "Nirvana", "Smells Like Teen Spirit"],
    [23, "Technotronic", "Pump Up The Jam"],
    [24, "DJ Jazzy Jeff & The Fresh Prince", "Summertime"],
    [25, "EMF", "Unbelievable"],
    [26, "Supergrass", "Feel Alright"],
    [27, "Spice Girls", "Wannabe"],
    [28, "Coolio", "Gangsters Paradise"],
    [29, "Everything But the Girl", "Missing"],
    [30, "Oasis", "Wonderwall"],
    [31, "Britney Spears", "Baby One More Time"],
    [32, "Cornershop", "Brimful of Asher"],
    [33, "Bjork", "Human Behaviour"],
    [34, "Arrested Development", "People Everyday"],
    [35, "Seal", "Kiss From A Rose"],
    [36, "Pulp", "Common People"],
    [37, "TLC", "No Scrubs"],
    [38, "Fugees", "Killing Me Softly"],
    [39, "Fun Lovin' Criminals", "Scooby Snacks"],
    [40, "Alanis Morissette", "Ironic"],
    [41, "Natalie Imbruglia", "Torn"],
    [42, "The Verve", "Bittersweet Symphony"],
    [43, "House of Pain", "Jump around"],
    [44, "REM", "Everybody Hurts"],
    [45, "MC Hammer", "You Can't Touch This"],
    [46, "Sinead O Connor", "Nothing Compares to You"],
    [47, "Cher", "Believe"],
    [48, "Coolio", "Gangsters paradise"],
    [49, "Jimmy Cliff", "I Can See Clearly Now"],
    [50, "Michael Jackson", "Black or White"],
    [51, "Jet", "Are You Gonna Be My Girl?"],
];