const nineties = [
    [1, "Radiohead", "Creep"],
    [2, "Eminem", "Slim Shady"],
    [3, "New Radicals", "You Get What You Give"],
    [4, "Sixpence None the Richer", "Kiss Me"],
    [5, "Ice Cube", "It Was a Good day"],
    [6, "Sir MixAlot", "Baby Got Back"],
    [7, "Joan Osborne", "One of Us"],
    [8, "Shania Twain", "That Don't Impress Me Much"],
    [9, "Wyclef Jean", "Staying Alive"],
    [10, "Snoop Doggy Dogg", "What's My Name"],
    [11, "Will Smith", "Gettin' Jiggy Wit It"],
    [12, "Cypress Hill", "Insane In the Brain"],
    [13, "Naughty by Nature", "OPP"],
    [14, "Foo Fighters", "Everlong"],
    [15, "En Vogue", "My Lovin'"],
    [16, "2 Pac", "California Love"],
    [17, "Blackstreet", "No Diggity"],
    [18, "Propellerheads", "History Repeating"],
    [19, "Ricky Martin", "Livin' La Vida Loca"],
    [20, "Sarah McLachlan", "Posession"],
    [21, "Hanson", "MMMBop"],
    [22, "Nirvana", "Smells Like Teen Spirit"],
    [23, "Technotronic", "Pump Up The Jam"],
    [24, "DJ Jazzy Jeff & The Fresh Prince", "Summertime"],
    [25, "EMF", "Unbelievable"],
    [26, "Supergrass", "Feel Alright"],
    [27, "Spice Girls", "Wannabe"],
    [28, "Coolio", "Gangsters Paradise"],
    [29, "Everything But the Girl", "Missing"],
    [30, "Oasis", "Wonderwall"],
    [31, "Britney Spears", "Baby One More Time"],
    [32, "Cornershop", "Brimful of Asher"],
    [33, "Bjork", "Human Behaviour"],
    [34, "Arrested Development", "People Everyday"],
    [35, "Seal", "Kiss From A Rose"],
    [36, "Pulp", "Common People"],
    [37, "TLC", "No Scrubs"],
    [38, "Fugees", "Killing Me Softly"],
    [39, "Fun Lovin' Criminals", "Scooby Snacks"],
    [40, "Alanis Morissette", "Ironic"],
    [41, "Natalie Imbruglia", "Torn"],
    [42, "The Verve", "Bittersweet Symphony"],
    [43, "House of Pain", "Jump around"],
    [44, "REM", "Everybody Hurts"],
    [45, "MC Hammer", "You Can't Touch This"],
    [46, "Sinead O Connor", "Nothing Compares to You"],
    [47, "Cher", "Believe"],
    [48, "Will Smith", "Miami"],
    [49, "Jimmy Cliff", "I Can See Clearly Now"],
    [50, "Michael Jackson", "Black or White"],
    [51, "Warren G, Nate Dogg", "Regulate"],
    [52, "Blind Melon", "No Rain"],
    [53, "Alanis Morissette", "Hand in My Pocket"],
    [54, "Alanis Morissette", "You Oughta Know"],
    [55, "Beastie Boys", "Sabotage"],
    [56, "Björk", "Big Time Sensuality"],
    [57, "Blur", "Song 2"],
    [58, "Crash Test Dummies", "Mmm Mmm Mmm Mmm"],
    [59, "Crowded House ", "Weather With You"],
    [60, "Deep Blue Something ", "Breakfast At Tiffany's"],
    [61, "Edwyn Collins ", "A Girl Like You"],
    [62, "Weezer", "Buddy Holly"],
    [63, "Enigma ", "Return To Innocence"],
    [64, "Hole ", "Celebrity Skin"],
    [65, "Hole ", "Malibu"],
    [66, "White Town", "Your Woman"],
    [67, "Ini Kamoze", "Here Comes the Hotstepper"],
    [68, "Madonna ", "Vogue"],
    [69, "Marcy Playground", "Sex & Candy"],
    [70, "Massive Attack", "Unfinished Sympathy"],
    [71, "Montell Jordan", "This Is How We Do It"],
    [72, "Nirvana", "Lithium"],
    [73, "Nirvana", "Where Did You Sleep Last Night"],
    [74, "Pearl Jam", "Alive"],
    [75, "PJ Harvey", "Down By The Water"],
    [76, "Portishead", "Sour Times"],
    [77, "Radiohead", "Paranoid Android"],
    [78, "Rammstein", "Du hast"],
    [79, "Red Hot Chili Peppers", "Give It Away"],
    [80, "Semisonic ", "Closing Time"],
    [81, "Sheryl Crow ", "If It Makes You Happy"],
    [82, "Simply Red ", "Stars"],
    [83, "Skee-LoI ", "Wish"],
    [84, "Snow ", "Informer"],
    [85, "Sting", "Englishman In New York"],
    [86, "Stone Temple Pilots", "Plush"],
    [87, "The Cardigans ", "Lovefool"],
    [88, "The Cranberries", "Dreams"],
    [89, "The Cranberries", "Linger"],
    [90, "The La's", "There She Goes"],
    [91, "The Notorious B.I.G., Mase, Diddy", "Mo Money Mo Problems"],
    [92, "The Notorious B.I.G., Pam Long", "Hypnotize"],
    [93, "The Prodigy", "Breathe"],
    [94, "The Prodigy", "Firestarter"],
    [95, "The Prodigy", "Smack My Bitch Up"],
    [96, "The Smashing Pumpkins", "1979"],
    [97, "Tori Amos", "Cornflake Girl"],





];