const protest = [
    [1, "Little Steven/Artists Against Apartheid", "(Ain't Going to Play) Sun City "],
    [2, "Talking Heads", "[Nothing But] Flowers"],
    [3, "Tennessee Ernie Ford ", "16 Tons"],
    [4, "Nena", "99 Red Balloons"],
    [5, "Sam Cooke   ", "A Change Is Gonna Come  "],
    [6, "Bob Dylan ", "A Hard Rain's A Gonna Fall"],
    [7, "Arlo Guthrie", "Alice's Restaurant"],
    [8, "Billy Joel   ", "Allentown  "],
    [9, "Kendrick Lamar   ", "Alright"],
    [10, "Stiff Little Fingers", "Alternative Ulster"],
    [11, "Eric Idle", "Always Look On The Bright Side Of Life "],
    [12, "Simon & Garfunkel   ", "America"],
    [13, "Green Day    ", "American Idiot "],
    [14, "Etta James", "At Last"],
    [15, "The Temptations   ", "Ball Of Confusion"],
    [16, "Joni Mitchell ", "Big Yellow Taxi"],
    [17, "Paul McCartney   ", "Blackbird"],
    [18, "Bob Dylan", "Blowing In The Wind"],
    [19, "Bruce Springsteen   ", "Born in the U.S.A.  "],
    [20, "Lady Gaga   ", "Born This Way"],
    [21, "Bing Crosby", "Brother Can You Spare A Dime "],
    [22, "Barry McGuire   ", "Eve Of Destruction"],
    [23, "Monty Python", "Every Sperm is Sacred  "],
    [24, "Leonard Cohen  ", "Everybody Knows"],
    [25, "Tracy Chapman     ", "Fast Car"],
    [26, "Country Joe Mcdonald  ", "Feel Like I'm Fixing to Die Rag"],
    [27, "Nina Simone     ", "Feeling Good"],
    [28, "Public Enemy   ", "Fight The Power  "],
    [29, "Buffalo Springfield   ", "For What It's Worth"],
    [30, "Creedence Clearwater Revival ", "Fortunate Son"],
    [31, "NWA ", "Fuck Tha Police"],
    [32, "Bob Marley  ", "Get Up Stand Up"],
    [33, "Sex Pistols   ", "God Save The Queen"],
    [34, "Jeannie C. Riley   ", "Harper Valley P.T.A."],
    [35, " Janelle Monae f. Wondaland", "HELL YOU TALMBOUT"],
    [36, "Helen Reddy   ", "I Am Woman"],
    [37, "Boomtown Rats", "I Don't Like Mondays"],
    [38, "Modern English  ", "I Melt With You"],
    [39, "Gloria Gaynor  ", "I Will Survive"],
    [40, "John Lennon & The Plastic Ono Band", "Imagine"],
    [41, "Nick Cave", "Into My Arms"],
    [42, "Rage Against The Machine  ", "Killing In the Name"],
    [43, "Roger Miller", "King of the Road"],
    [44, "The Kinks   ", "Lola"],
    [45, "Suzanne Vega   ", "Luka"],
    [46, "Kingston Trio", "M.T.A. "],
    [47, "Marvin Gaye   ", "Mercy Mercy Me"],
    [48, "Nina Simone ", "Mississippi Goddam"],
    [49, "The Who   ", "My Generation"],
    [50, "Bessie Smith", "Nobody Knows You When You're Down and Out"],
    [51, "The (Dixie) Chicks   ", "Not Ready To Make Nice  "],
    [52, "Laurie Anderson    ", "O Superman"],
    [53, "Crosby, Stills, Nash, and Young ", "Ohio"],
    [54, "Paul Robeson", "Ol' Man River"],
    [55, "M.I.A.", "Paper Planes"],
    [56, "John Prine", "Paradise"],
    [57, "Curtis Mayfield   ", "People Get Ready"],
    [58, "Foster The People    ", "Pumped Up Kicks "],
    [59, "Bikini Kill   ", "Rebel Girl"],
    [60, "Frankie Goes To Hollywood ", "Relax  "],
    [61, "Aretha Franklin  ", "Respect  "],
    [62, "The Beatles   ", "Revolution"],
    [63, "Lorde ", "Royals"],
    [64, " James Brown", "Say it Loud  I'm Black and Proud"],
    [65, "Randy Newman   ", "Short People  "],
    [66, "The (English) Beat   ", "Stand Down Margaret"],
    [67, "Billie Holiday", "Strange Fruit"],
    [68, "Bruce Springsteen   ", "Streets of Philadelphia  "],
    [69, "U2  ", "Sunday Bloody Sunday"],
    [70, "Hozier   ", "Take Me To Church"],
    [71, "Tracy Chapman  ", "Talkin' About A Revolution  "],
    [72, "The Beatles", "Taxman"],
    [73, "Jimmy Cliff ", "The Harder They Come "],
    [74, "The Eagles", "The Last Resort"],
    [75, "Grand Master Flash & The Furious Five   ", "The Message"],
    [76, "Gil Scott Heron   ", "The Revolution Will Not Be Televised"],
    [77, "Jimi Hendrix   ", "The Star Spangled Banner"],
    [78, "Bob Dylan", "The Times They Are a Changin'"],
    [79, "Childish Gambino   ", "This Is America"],
    [80, "Woody Guthrie  ", "This Land Is Your Land"],
    [81, "Til Tuesday   ", "Voices Carry"],
    [82, "Lou Reed", "Walk on the Wild Side"],
    [83, "Edwin Starr   ", "War"],
    [84, "Tom Lehrer", "We Will All Go Together When We Go"],
    [85, "Mickey Guyton   ", "What Are You Gonna Tell Her?"],
    [86, "The Tubes", "What Do You Want From Life?"],
    [87, "Joan Baez", "What Have They Done To The Rain?"],
    [88, "Marvin Gaye  ", "What's Going On"],
    [89, "Cat Stevens   ", "Where Do The Children Play?"],
    [90, "Paula Cole  ", "Where Have All the Cowboys Gone?"],
    [91, "Pete Seeger", "Where Have All The Flowers Gone?"],
    [92, "Tim Minchin", "White Wine In The Sun "],
    [93, "The Who", "Won't Get Fooled Again"],
    [94, "Lesley Gore   ", "You Don't Own Me"],
    [95, "Bob & Marcia   ", "Young, Gifted and Black"],
    [96, "The Cranberries   ", "Zombie"]
];