const rock = [
    [1, "Kings of Leon", "Sex on Fire"],
    [2, "Evanescence", "Bring Me to Life"],
    [3, "Jerry Lee Lewis", "Great Balls of Fire"],
    [4, "Focus", "Hocus Pocus"],
    [5, "Sum 41", "Fat Lip"],
    [6, "Chris Cornell", "You Know My Name"],
    [7, "Black Sabbath", "Paranoid"],
    [8, "Darkness", "Thing Called Love"],
    [9, "Oasis", "Cigarettes & Alcohol"],
    [10, "Bon Jovi", "Livin' on a Prayer"],
    [11, "Green Day", "Welcome to Paradise"],
    [12, "Cream", "Sunshine of your Love"],
    [13, "Jimi Hendrix", "Voodoo Chile"],
    [14, "Franz Ferdinand", "Take Me Out"],
    [15, "Guns N Roses", "Sweet Child of Mine"],
    [16, "Bloodhound Gang", "Discovery Channel"],
    [17, "Bon Jovi", "Keep the Faith"],
    [18, "Bush", "The Chemicals Between Us"],
    [19, "Queen", "I Want to Ride My Bicycle"],
    [20, "Bachman Turner Overdrive", "You Ain't Seen Nothin' Yet"],
    [21, "Lynrd Skynrd", "Free Bird"],
    [22, "AC/DC", "Hells Bells"],
    [23, "Heart", "Barracuda"],
    [24, "Dead or Alive", "You Spin Me Round"],
    [25, "Red Hot Chilli Peppers", "Under the Bridge"],
    [26, "Tenatious D", "Tribute"],
    [27, "Bon Jovi", "Have a Nice Day"],
    [28, "Red Hot Chilli Peppers", "By the Way"],
    [29, "Razorlight", "America"],
    [30, "Heart", "Crazy on You"],
    [31, "Kaiser Chiefs", "I Predict A Riot"],
    [32, "Alice Cooper", "Eighteen"],
    [33, "Queen", "Don't Stop Me Now"],
    [34, "Foo Fighters", "Breakout"],
    [35, "Nirvana", "Smells Like Teen Spirit"],
    [36, "Kiss", "God Gave Rock & Roll to You"],
    [37, "Europe", "The Final Countdown"],
    [38, "Nirvana", "Come As You Are"],
    [39, "The Offspring", "Self Esteem"],
    [40, "Wheatus", "Teenage Dirtbag"],
    [41, "Allman Brothers", "Jessica"],
    [42, "Kid Rock", "All Summer Long"],
    [43, "Guns N Roses", "Paradise City"],
    [44, "Megadeth", "Skin of My Teeth"],
    [45, "Neil Young", "Like a Hurricane"],
    [46, "Korn", "Blind"],
    [47, "Nirvana", "Heart Shaped Box"],
    [48, "Kings of Leon", "Use Somebody"],
    [49, "Stone Roses", "Fools Gold"],
    [50, "Emerson, Lake and Palmer", "Lucky Man"],
    [51, "David Bowie", "Panic in Detroit"],
    [52, "Rage Against the Machine", "Killing in the Name"],
    [53, "The Offspring", "Pretty Fly (for a White Guy)"],
    [54, "Jimi Hendrix", "Purple Haze"],
    [55, "Lenny Kravitz", "Always on the Run"],
    [56, "Golden Earring", "Radar Love"],
    [57, "Iron Maiden", "Fear of the Dark"],
    [58, "Iron Maiden", "Run to the Hills"],
    [59, "Queens of the Stone Age", "No One Knows"],
    [60, "Aerosmith", "Love in an Elevator"],
    [61, "Foo Fighters", "Monkey Wrench"],
    [62, "Lenny Kravitz", "Are You Gonna Go My Way"],
    [63, "Deep Purple", "Smoke on the Water"],
    [64, "Primal Scream", "Rocks"],
    [65, "Free", "All Right Now"],
    [66, "Steppenwolf", "Born To Be Wild"],
    [67, "The Jam", "Going Underground"],
    [68, "Neil Young", "Rockin' in the Free World"],
    [69, "AC/DC", "Highway to Hell"],
    [70, "Rolling Stones", "(I Can't Get No) Satisfaction"],
    [71, "Santana", "Soul Sacrifice"],
    [72, "David Bowie", "Suffragette City"],
    [73, "Led Zeppelin", "Stairway to Heaven"],
    [74, "Deep Purple", "Black Night"],
    [75, "Allman Brothers", "Ramblin' Man"],
    [76, "Foo Fighters", "Best of You"],
    [77, "Smashing Pumpkins", "Today"],
    [78, "Foo Fighters", "My Hero"],
    [79, "Beatles", "Helter Skelter"],
    [80, "Guns 'n' Roses", "November Rain"],
    [81, "Guns 'n' Roses", "You Could Be Mine"],
    [82, "The Scorpions", "Wind of Change"],
    [83, "Ted Nugent", "Cat Scratch Fever"],
    [84, "Bob Dylan", "Hurricane"],
    [85, "Metallica", "Nothing Else Matters"],
    [86, "Green Day", "Longview"],
    [87, "Sum 41", "In Too Deep"],
    [88, "ZZ Top", "Sharp Dressed Man"],
    [89, "Blink 182", "All the Small Things"],
    [90, "Pearl Jam", "Yellow Ledbetter"],
    [91, "Green Day", "American Idiot"],
    [92, "Nirvana", "In Bloom"],
    [93, "The White Stripes", "Seven Nation Army"],
    [94, "Alice Cooper", "Elected"],
    [95, "Alice Cooper", "Schools Out"],
    [96, "Bad Company", "Feel Like Making Love"],
    [97, "George Thorogood", "Bad to the Bone"],
    [98, "Led Zeppelin", "Black Dog"],
    [99, "Led Zeppelin", "Kashmir"],
    [100, "Chicago", "25 or 6 to 4"],
    [101, "Journey", "Don't Stop Believin'"],
    [102, "Edgar Winter Group", "Frankenstein"],
    [103, "Aerosmith", "Sweet Emotion"],




];