const seventies = [
    [1, "Iggy Pop", "Lust For Life"],
    [2, "Tony Christie", "Amarillo"],
    [3, "Elton John", "Rocketman"],
    [4, "Abba", "Mama Mia"],
    [5, "Bob Marley", "One Love"],
    [6, "Queen", "Bohemian Rhapsody"],
    [7, "The Beatles", "Let It Be"],
    [8, "Donna Summer", "Hot stuff"],
    [9, "Hot Chocolate", "You Sexy Thing"],
    [10, "Barry White", "My First, My Last, My Everything"],
    [11, "Pink Floyd", "Another Brick in the Wall"],
    [12, "Bee Gees", "Night Fever"],
    [13, "Kool & The Gang", "Jungle Boogie"],
    [14, "Donna Summer", "I Feel Love"],
    [15, "Frank Sinatra", "New York New York"],
    [16, "Wild Cherry", "Play that Funky Music"],
    [17, "Curtis Mayfield", "Move On Up"],
    [18, "Ian Drury & the Blockheads", "Hit Me with your Rythm Stick"],
    [19, "Undertones", "Teenage Kicks"],
    [20, "Bob Marley", "No Woman No Cry"],
    [21, "Stevie Wonder", "Superstition"],
    [22, "Elton John", "Crocodile Rock"],
    [23, "Eagles", "Hotel California"],
    [24, "Buggles", "Video Killed the Radio Star"],
    [25, "Buzzcocks", "Ever Fallen in Love (With Someone You Shouldn't've)"],
    [26, "Lynard Skynard", "Sweet Home Alabama"],
    [27, "Gary Numan", "Cars"],
    [28, "Boston", "More Than a Feeling"],
    [29, "Al Green", "Let's Stay Together"],
    [30, "Led Zeppelin", "Stairway to Heaven"],
    [31, "David Bowie", "Starman"],
    [32, "Stevie Wonder", "Superstition"],
    [33, "Marvin Gaye", "Let's Get it On"],
    [34, "Bruce Springsteen", "Born to Run"],
    [35, "Abba", "Dancing Queen"],
    [36, "Boney M", "Rivers of Babylon"],
    [37, "Michael Jackson", "Don't Stop Til You Get Enough"],
    [38, "The Clash", "London Calling"],
    [39, "Elton John", "Tiny Dancer"],
    [40, "Bee Gees", "You Should Be Dancing"],
    [41, "The Real Thing", "You to me are Everything"],
    [42, "Starland Vocal Band", "Afternoon Delight"],
    [43, "Elton John", "Saturday Night's Alright For Fighting"],
    [44, "Queen", "We Will Rock You"],
    [45, "Chaka Khan", "I'm Every Woman"],
    [46, "Sylvester", "You Make Me Feel"],
    [47, "Buzzcocks", "Ever Fallen In Love (With Someone You Shouldn't've)"],
    [48, "Joni Mitchell", "Big Yellow Taxi"],
    [49, "The Knack", "My Sharona"],
    [50, "Carl Douglas", "Kung Fu Fighting"]


];