const sixties = [
    [1, "Dusty Springfield", "Son of a Preacher Man"],
    [2, "James Brown", "Papa's Got a Brand New Bag"],
    [3, "Elvis", "Suspicious Minds"],
    [4, "Foundations", "Build me up Buttercup"],
    [5, "Louis Armstrong", "What a Wonderful World"],
    [6, "Yusuf, Cat Stevens", "The First Cut Is The Deepest"],
    [7, "Supremes", "Baby Love"],
    [8, "Bob Dylan", "Mr Tambourine Man"],
    [9, "Nancy Sinatra", "Bang Bang(Shot You Down)"],
    [10, "The Beatles", "Yellow Submarine"],
    [11, "The Beatles", "Twist & Shout"],
    [12, "The Ronettes", "Be My Baby"],
    [13, "Elvis Presley", "Can't Help Falling in Love"],
    [14, "The Beatles", "Hey Jude"],
    [15, "The Beatles", "Ob La Di Ob La Da"],
    [16, "The Isley Brothers", "Twist and Shout"],
    [17, "The Beatles", "Lucy in the Sky with Diamonds"],
    [18, "Ben E King", "Stand By me"],
    [19, "Norman Greenbaum", "Spirit In the Sky"],
    [20, "The Monkees", "I'm a Believer"],
    [21, "Manfred Mann", "Do Wah Diddy Diddy"],
    [22, "Herman's Hermits", "I'm Into Something Good"],
    [23, "Sonny & Cher", "I Got You Babe"],
    [24, "The Four Tops", "Reach Out, I'll Be There"],
    [25, "The Shadows", "Apache"],
    [26, "The Impressions", "People Get Ready"],
    [27, "The Archies", "Sugar Sugar"],
    [28, "The Troggs", "Wild Thing"],
    [29, "Chubby Checker", "Let's Twist Again"],
    [30, "Petula Clark", "Downtown"],
    [31, "The Kinks", "All Day and All of the Night"],
    [32, "Aretha Franklin", "Respect"],
    [33, "The Animals", "The House of the Rising Sun"],
    [34, "Booker T and the MGs", "Green Onions"],
    [35, "Wilson Pickett", "Land of a Thousand Dances"],
    [36, "Johnny Kidd and the Pirates", "Shakin' All Over"],
    [37, "The Righteous Brothers", "Unchained Melody"],
    [38, "Otis Redding", "The Dock of the Bay"],
    [39, "The Animals", "We've Gotta Get Out of this Place"],
    [40, "Status Quo", "Pictures of Matchstick Men"],
    [41, "Marvin Gaye", "I Heard it Through the Grapevine"],
    [42, "The Beach Boys", "Good Vibrations"],
    [43, "Roy Orbison", "Pretty Woman"],
    [44, "The Monkees", "Daydream Believer"],
    [45, "Gene Pitney", "Something's Gotten Hold of my Heart"],
    [46, "The Crystals", "Then He Kissed Me"],
    [47, "The Hollies", "He Ain't Heavy He's My Brother"],
    [48, "Percy Sledge", "When a Man Loves a Woman"],
    [49, "Aretha Franklin", "I Say a Little Player"],
    [50, "Desmond Decker and The Aces", "Israelites"],
    [51, "David Bowie", "Space Oddity"],
    [52, "Aretha Franklin", "Chain of Fools"],
    [53, "Janis Joplin", "Piece of My Heart"],
    [54, "Bob Dylan", "I Want You"],
    [55, "Bob Dylan", "Positively 4th Street"],
    [56, "Bob Dylan", "Tangled up in Blue"],
    [57, "Cream", "I Feel Free"],
    [58, "The Beatles", "You've Got To Hide Your Love Away"],
    [59, "Creedence Clearwater Revival", "Born On The Bayou"],
    [60, "Crosby, Stills & Nash", "Suite, Judy Blue Eyes"],
    [61, "Crosby, Stills, Nash & Young", "Teach Your Children"],
    [62, "Donovan", "Hurdy Gurdy Man"],
    [63, "The Doors", "Alabama Song (Whisky Bar)"],
    [64, "Fleetwood Mac", "Albatross"],
    [65, "Fleetwood Mac", "Black Magic Woman"],
    [66, "The Byrds", "Turn! Turn! Turn! (To Everything There Is a Season)"],
    [67, "Four Tops", "Bernadette"],
    [68, "Frank Sinatra", "Summer Wind"],
    [69, "Glen Campbell", "Wichita Lineman"],
    [70, "The Box Tops", "The Letter"],
    [71, "Jefferson Airplane", "White Rabbit"],
    [72, "Jimi Hendrix", "The Wind Cries Mary"],
    [73, "Joe Cocker", "With A Little Help From My Friends"],
    [74, "Simon & Garfunkel", "April Come She Will"],
    [75, "The Rolling Stones", "Ruby Tuesday"],
    [76, "Simon & Garfunkel", "I Am a Rock"],
    [77, "Simon & Garfunkel", "The 59th Street Bridge Song (Feelin' Groovy)"],
    [78, "Smith", "Baby It's You"],
    [79, "The Band", "The Weight"],
    [80, "The Beach Boys", "Sloop John B"],
    [81, "The Beatles", "Drive My Car"],
    [82, "The Beatles", "I Am The Walrus"],
    [83, "The Beatles", "Norwegian Wood (This Bird Has Flown)"],
    [84, "The Beatles", "You Never Give Me Your Money"],
    [85, "The Who", "I Can See For Miles"],
    [86, "The Who", "I'm Free"],
    [87, "Thunderclap Newman", "Something in the Air"],
    [88, "Tommy James & The Shondells", "I Think We're Alone Now"],





];