const twentyTwenties = [
    [1, "Cash Cash & Andy Grammer", "I Found You"],
    [2, "Drake", "Toosie Slide"],
    [3, "Dua Lipa", "Physical"],
    [4, "Joel Corry", "Lonely"],
    [5, "Jonas Brothers", "What a Man Gotta Do"],
    [6, "Lady Gaga & Ariana Grande", "Rain On Me"],
    [7, "Marshmello & Halsey", "Be Kind"],
    [8, "Pussycat Dolls", "React"],
    [9, "Sia", "Together"],
    [10, "Times Like These", "Live Lounge Allstars"],
    [11, "Dua Lipa", "Levitating"],
    [12, "Ed Sheeran", "Afterglow"],
    [13, "Harry Styles", "Watermelon Sugar"],
    [14, "Internet Money & Gunna", "Lemonade"],
    [15, "Jason Derulo", "Love Not War (The Tampa Beat)"],
    [16, "Joel Corry & MNEK", "Head And Heart"],
    [17, "Justin Bieber", "Anyone"],
    [18, "Keith Urban & P!nk", "One Too Many"],
    [19, "KSI", "Really Love"],
    [20, "Meduza", "Paradise"],
    [21, "Miley Cyrus", "Prisoner"],
    [22, "Sam Smith", "Diamonds"],
    [23, "Taylor Swift", "Willow"],
    [24, "The Kid Laroi", "Without You"],
    [25, "24k Goldn", "Mood"],
    [26, "Anne-Marie x KSI x Digital Farm Animals", "Don't Play"],
    [27, "Billie Eilish", "Therefore I Am"],
    [28, "Clean Bandit & Mabel", "Tick Tock"],
    [29, "Justin Bieber", "Anyone"],
    [30, "Lil Nas X", "That's What I Want"],
    [31, "Mimi Webb", "24slash5"],
    [32, "Tom Grennan", "Don't Break The Heart"],
    [33, "Adele", "Easy on Me"],
    [34, "Kygo", "Undeniable"],
    [35, "Coldplay & Selima Gomez", "Let Somebody Go"],
    [36, "Diplo, Paul Woolford & Kareen Lomax", "Promises"],
    [37, "Ed Sheeran", "Bad Habits"],
    [38, "Years and Years", "American Boy"],
    [39, "Jesy Nelson feat Nicki Minaj", "Boyz"],
    [40, "Ed Sheeran", "Shivers"],
    [41, "Central Cee", "Obsessed With You"],
    [42, "Joel Corry, Jax Jones, Charli XCX & Saweetie", "Out Out"],
    [43, "Little Simz", "Introvert"],
    [44, "The Kid LAROI & Justin Bieber", "Stay"],
    [45, "Nathan Dawe & T Matthias", "Goodbye"],
    [46, "Whitney Houston & Clean Bandit", "How Will I Know"],
    [47, "Maneskin", "Mammamia"],
    [48, "Pa Salieu Feat Aitch", "Bad"],
    [49, "Zoe Wees Feat. 6lack", "That's How It Goes"],
    [50, "Dua Lipa & Elton John", "Coldheart"],
    [51, "Anitta & Saweetie", "Faking Love"],
    [52, "Mahalia Ft AJ Tracey", "Roadside"],
    [53, "The Weeknd", "Take my Breath"],
    [54, "Coldplay X BTS", "My Universe"],
    [55, "Arlo Parks", "Hope"],
    [56, "Lil Nas X", "Montero (Call me by Your Name)"],
    [57, "Glass Animals", "Heat Waves"]
];