const twentyTwenties = [
    [1, "Cash Cash & Andy Grammer", "I Found You"],
    [2, "Drake", "Toosie Slide"],
    [3, "Dua Lipa", "Physical"],
    [4, "Joel Corry", "Lonely"],
    [5, "Jonas Brothers", "What a Man Gotta Do"],
    [6, "Lady Gaga & Ariana Grande", "Rain On Me"],
    [7, "Marshmello & Halsey", "Be Kind"],
    [8, "Pussycat Dolls", "React"],
    [9, "Sia", "Together"],
    [10, "Times Like These", "Live Lounge Allstars"],
    [11, "Dua Lipa", "Levitating"],
    [12, "Ed Sheeran", "Afterglow"],
    [13, "Harry Styles", "Watermelon Sugar"],
    [14, "Internet Money & Gunna", "Lemonade"],
    [15, "Jason Derulo", "Love Not War (The Tampa Beat)"],
    [16, "Joel Corry & MNEK", "Head And Heart"],
    [17, "Justin Bieber", "Anyone"],
    [18, "Keith Urban & P!nk", "One Too Many"],
    [19, "KSI", "Really Love"],
    [20, "Meduza", "Paradise"],
    [21, "Miley Cyrus", "Prisoner"],
    [22, "Sam Smith", "Diamonds"],
    [23, "Taylor Swift", "Willow"],
    [24, "The Kid Laroi", "Without You"],
    [25, "24k Goldn", "Mood"],
    [26, "Anne-Marie x KSI x Digital Farm Animals", "Don't Play"],
    [27, "Billie Eilish", "Therefore I Am"],
    [28, "Clean Bandit & Mabel", "Tick Tock"],
    [29, "Masked Wolf", "Astronaut in the Ocean "],
    [30, "Lil Nas X", "That's What I Want"],
    [31, "Mimi Webb", "24/5"],
    [32, "Tom Grennan", "Don't Break The Heart"],
    [33, "Adele", "Easy on Me"],
    [34, "Kygo", "Undeniable"],
    [35, "Coldplay & Selima Gomez", "Let Somebody Go"],
    [36, "Diplo, Paul Woolford & Kareen Lomax", "Promises"],
    [37, "Ed Sheeran", "Bad Habits"],
    [38, "Years and Years", "American Boy"],
    [39, "Jesy Nelson feat Nicki Minaj", "Boyz"],
    [40, "Ed Sheeran", "Shivers"],
    [41, "Central Cee", "Obsessed With You"],
    [42, "Joel Corry, Jax Jones, Charli XCX & Saweetie", "Out Out"],
    [43, "Little Simz", "Introvert"],
    [44, "The Kid LAROI & Justin Bieber", "Stay"],
    [45, "Nathan Dawe & T Matthias", "Goodbye"],
    [46, "Whitney Houston & Clean Bandit", "How Will I Know"],
    [47, "Maneskin", "Mammamia"],
    [48, "Pa Salieu Feat Aitch", "Bad"],
    [49, "Zoe Wees Feat. 6lack", "That's How It Goes"],
    [50, "Dua Lipa & Elton John", "Coldheart"],
    [51, "Anitta & Saweetie", "Faking Love"],
    [52, "Mahalia Ft AJ Tracey", "Roadside"],
    [53, "The Weeknd", "Take my Breath"],
    [54, "Coldplay X BTS", "My Universe"],
    [55, "Arlo Parks", "Hope"],
    [56, "Lil Nas X", "Montero (Call me by Your Name)"],
    [57, "Glass Animals", "Heat Waves"],
    [58, "Mariah Carey", "All I Want for Christmas Is You"],
    [59, "Post Malone", "Circles"],
    [60, "Roddy Ricch", "The Box"],
    [61, "Dua Lipa", "Don't Start Now"],
    [62, "DaBaby featuring Roddy Ricch", "Rockstar"],
    [63, "Gabby Barrett featuring Charlie Puth", "I Hope"],
    [64, "Future featuring Drake", "Life Is Good"],
    [65, "Maroon 5", "Memories"],
    [66, "Maren Morris", "The Bones"],
    [67, "Kate Bush", "Running Up That Hill"],
    [68, "Doja Cat", "Say So"],
    [69, "Ariana Grande", "Positions"],
    [70, "Jack Harlow featuring DaBaby, Tory Lanez and Lil Wayne", "Whats Poppin"],
    [71, "“Encanto” Cast", "We Don't Talk About Bruno"],
    [72, "Megan Thee Stallion featuring Beyonce", "Savage"],
    [73, "Arizona Zervas", "Roxanne"],
    [74, "Justin Bieber featuring Quavo", "Intentions"],
    [75, "Billie Eilish", "Everything I Wanted"],
    [76, "Saint Jhn", "Roses (Imanbek Remix)"],
    [77, "The Weeknd and Ariana Grande", "Save Your Tears"],
    [78, "Chris Brown and Young Thug", "Go Crazy"],
    [79, "Olivia Rodrigo", "Good 4 U"],
    [80, "Doja Cat featuring SZA", "Kiss Me More"],
    [81, "Silk Sonic (Bruno Mars and Anderson .Paak)", "Leave the Door Open"],
    [82, "Olivia Rodrigo", "Drivers License"],
    [83, "Justin Bieber featuring Daniel Caesar and Giveon", "Peaches"],
    [84, "BTS", "Butter"],
    [85, "Luke Combs", "Forever After All"],
    [86, "Olivia Rodrigo", "Deja Vu"],
    [87, "Harry Styles", "Adore You"],
    [88, "Taylor Swift", "Anti-Hero"],
    [89, "Sam Smith and Kim Petras", "Unholy"],
    [90, "Steve Lacy", "Bad Habit"],
    [91, "Nicki Minaj", "Super Freaky Girl"],
    [92, "Beyonce", "Break My Soul"],
    [93, "Lizzo", "About Damn Time"],
    [94, "Drake featuring 21 Savage", "Jimmy Cooks"],
    [95, "Future featuring Drake and Tems", "Wait for U"],
    [96, "Jack Harlow", "First Class"],
    [97, "Harry Styles", "As It Was"],




];