const twoThousands = [
    [1, "Daft Punk", "Digital Love"],
    [2, "Kylie Minogue", "Can't Get You Out of My Head"],
    [3, "Madonna", "Music"],
    [4, "Sugarbabes", "Round Round"],
    [5, "Britney Spears", "Toxic"],
    [6, "Bassment Jaxx", "Wheres Your Head At"],
    [7, "Coldplay", "Yellow"],
    [8, "Outkast", "Hey Ya!"],
    [9, "Nelly Furtado", "Hot In Here"],
    [10, "Eminem", "Lose Yourself"],
    [11, "Shakira", "Underneath Your Clothes"],
    [12, "The Killers", "Mr Brightside"],
    [13, "Ice Cube", "You Can Do It"],
    [14, "Coldplay", "Yellow"],
    [15, "David Gray", "Sail Away"],
    [16, "The Dandy Warhols", "Bohemian Like You"],
    [17, "Jet", "Are You Gonna Be My Girl"],
    [18, "Justin Timberlake", "Cry Me a River"],
    [19, "Norah Jones", "I Don't Know Why"],
    [20, "The Killers", "Somebody Told Me"],
    [21, "Usher", "Yeah!"],
    [22, "Keane", "Somewhere Only You Know"],
    [23, "Destiny's Child", "Bootylicious"],
    [24, "Ozone", "Dragostea Din Tei"],
    [25, "Coldplay", "Fix You"],
    [26, "Pink", "Get the Party Started"],
    [27, "Busted", "You Said No"],
    [28, "Gnarls Barkley", "Crazy"],
    [29, "Pink", "Just Like A Pill"],
    [30, "Amy Winehouse", "Rehab"],
    [31, "Christina Aguilera", "Beautiful"],
    [32, "Justin Timberlake", "Like I Love You"],
    [33, "The Killers", "Human"],
    [34, "Avril Lavigne", "Girlfriend"],
    [35, "Moby", "Natural Blues"],
    [36, "Rihanna", "Umbrella"],
    [37, "Gorillaz", "Kids with Guns"],
    [38, "Duffy", "Mercy"],
    [39, "Beyonce", "Crazy in Love"],
    [40, "Arctic Monkeys", "I Bet You Look Good on the Dance Floor"],
    [41, "Crazy Frog", "Axel F"],
    [42, "Goldfrapp", "Ooh La La"],
    [43, "Gwen Stefani", "Hollaback Girl"],
    [44, "Kelis", "Milkshake"],
    [45, "The White Stripes", "7 Nation Army"],
    [46, "Avril Lavigne", "My Happy Ending"],
    [47, "Maroon 5", "She Will Be Loved"],
    [48, "Alicia Keys & Jay Z", "Empire State of Mind"],
    [49, "Destiny's Child", "Survivor"],
    [50, "Pussycat Dolls", "Don't Cha"],
    [51, "Pink", "So What"],
    [52, "KT Tunstall", "Suddenly I See"],
    [53, "Lady Gaga", "Bad Romance"],
    [54, "Lady Gaga", "Just Dance"],
    [55, "Elbow", "One Day Like This"],
    [56, "Justin Timberlake feat. Timbaland", "SexyBack"],
    [57, "Shakira, Wyclef Jean", "Hips Don't Lie"],
    [58, "Coldplay", "Viva La Vida"],
    [59, "Plain White T's", "Hey There Delilah"],
    [60, "Gorillaz", "Feel Good Inc"]

];