const twoThousands = [
    [1, "Daft Punk", "Digital Love"],
    [2, "Kylie Minogue", "Can't Get You Out of My Head"],
    [3, "Madonna", "Music"],
    [4, "Sugarbabes", "Round Round"],
    [5, "Britney Spears", "Toxic"],
    [6, "Bassment Jaxx", "Where's Your Head At"],
    [7, "Coldplay", "Yellow"],
    [8, "Outkast", "Hey Ya!"],
    [9, "Nelly Furtado", "Hot In Here"],
    [10, "Eminem", "Lose Yourself"],
    [11, "Shakira", "Underneath Your Clothes"],
    [12, "The Killers", "Mr. Brightside"],
    [13, "Ice Cube", "You Can Do It"],
    [14, "Gorillaz", "Feel Good Inc"],
    [15, "David Gray", "Sail Away"],
    [16, "The Dandy Warhols", "Bohemian Like You"],
    [17, "Jet", "Are You Gonna Be My Girl"],
    [18, "Justin Timberlake", "Cry Me a River"],
    [19, "Norah Jones", "I Don't Know Why"],
    [20, "The Killers", "Somebody Told Me"],
    [21, "Usher", "Yeah!"],
    [22, "Keane", "Somewhere Only You Know"],
    [23, "Destiny's Child", "Bootylicious"],
    [24, "Ozone", "Dragostea Din Tei"],
    [25, "Coldplay", "Fix You"],
    [26, "P!nk", "Get the Party Started"],
    [27, "Busted", "You Said No"],
    [28, "Gnarls Barkley", "Crazy"],
    [29, "P!nk", "Just Like A Pill"],
    [30, "Amy Winehouse", "Rehab"],
    [31, "Christina Aguilera", "Beautiful"],
    [32, "Justin Timberlake", "Like I Love You"],
    [33, "The Killers", "Human"],
    [34, "Avril Lavigne", "Girlfriend"],
    [35, "Moby", "Natural Blues"],
    [36, "Rihanna", "Umbrella"],
    [37, "Gorillaz", "Kids with Guns"],
    [38, "Duffy", "Mercy"],
    [39, "Beyonce", "Crazy in Love"],
    [40, "Arctic Monkeys", "I Bet You Look Good on the Dance Floor"],
    [41, "Crazy Frog", "Axel F"],
    [42, "Goldfrapp", "Ooh La La"],
    [43, "Gwen Stefani", "Hollaback Girl"],
    [44, "Kelis", "Milkshake"],
    [45, "The White Stripes", "7 Nation Army"],
    [46, "Avril Lavigne", "My Happy Ending"],
    [47, "Maroon 5", "She Will Be Loved"],
    [48, "Alicia Keys & Jay Z", "Empire State of Mind"],
    [49, "Destiny's Child", "Survivor"],
    [50, "Pussycat Dolls", "Don't Cha"],
    [51, "P!nk", "So What"],
    [52, "KT Tunstall", "Suddenly I See"],
    [53, "Lady Gaga", "Bad Romance"],
    [54, "Lady Gaga", "Just Dance"],
    [55, "Elbow", "One Day Like This"],
    [56, "Justin Timberlake feat. Timbaland", "SexyBack"],
    [57, "Shakira, Wyclef Jean", "Hips Don't Lie"],
    [58, "Coldplay", "Viva La Vida"],
    [59, "Plain White T's", "Hey There Delilah"],
    [60, "Avril Lavigne", "Sk8er Boi"],
    [61, "Backstreet Boys", "I Want It That Way"],
    [62, "Beyoncé", "Single Ladies (Put a Ring on It)"],
    [63, "Black Eyed Peas", "Boom Boom Pow"],
    [64, "Black Eyed Peas", "I Gotta Feeling"],
    [65, "Britney Spears", "Womanizer"],
    [66, "Christina Aguilera, Redman", "Dirrty"],
    [67, "Fall Out Boy", "Sugar, We're Goin Down"],
    [68, "Fergie, Ludacris", "Glamorous"],
    [69, "Flo Rida, T-Pain", "Low"],
    [70, "Justin Bieber, Ludacris", "Baby"],
    [71, "Justin Timberlake", "Rock Your Body"],
    [72, "Kanye West", "Stronger"],
    [73, "Kanye West, Jamie Foxx", "Gold Digger"],
    [74, "Katy Perry", "Hot N Cold"],
    [75, "Kelly Clarkson", "Because of You"],
    [76, "Kesha", "TiK ToK"],
    [77, "Lady Gaga", "Poker Face"],
    [78, "Leona Lewis", "Bleeding Love"],
    [79, "Metro Station", "Shake It"],
    [80, "Miley Cyrus", "Party In The U.S.A"],
    [81, "Nelly Furtado, Timbaland", "Promiscuous"],
    [82, "One Direction", "What Makes You Beautiful"],
    [83, "Outkast", "Ms. Jackson"],
    [84, "Pitbull, Kesha", "Timber"],
    [85, "Pitbull, Ne-Yo, Afrojack, Nayer", "Give Me Everything"],
    [86, "Rec Hall", "She Doesn't Get It"],
    [87, "Rihanna", "Don't Stop The Music"],
    [88, "Rihanna", "Pon de Replay"],
    [89, "Rihanna", "SOS"],
    [90, "Sean Kingston", "Beautiful Girls"],
    [91, "Sean Paul", "Temperature"],
    [92, "Shaggy, Rik Rok", "It Wasn't Me"],
    [93, "Snoop Dogg, Pharrell Williams", "Drop It Like It's Hot"],
    [94, "Soulja Boy", "Crank That (Soulja Boy)"],
    [95, "Taio Cruz", "Dynamite"],
    [96, "The White Stripes", "Fell In Love With a Girl"],
    [97, "Train", "Hey, Soul Sister"],
    [98, "Usher, Pitbull", "DJ Got Us Fallin' In Love"],
    [99, "will.i.am, Britney Spears", "Scream & Shout"],



];